DROP TABLE sessions;
ALTER TABLE `accounts` ADD `session` BIGINT UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `accounts` ADD `loggedIn` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `items` ADD `tags` TEXT NOT NULL;
