ALTER TABLE  `characters` ADD  `pvpWins` BIGINT( 10 ) UNSIGNED NOT NULL DEFAULT  '0',
ADD  `pvpLosses` BIGINT( 10 ) UNSIGNED NOT NULL DEFAULT  '0',
ADD  `evGEnabled` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  '0',
ADD  `evGSupportRace` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  '0',
ADD  `transPvPEnabled` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  '0',
ADD  `causeOfDeath` INT NOT NULL DEFAULT  '0';